### ISSUE TITLE
Inconsistent licenses

### ISSUE THREAD

**Issue by AlvaroBrey** [rcgroot/adb-awake#1]
Hello, first of all many thanks for your work on this useful app. I want to contribute, but I couldn't help but notice some inconsistencies on your license headers. Here's one:

```
/*------------------------------------------------------------------------------
 **    Author: René de Groot
 ** Copyright: (c) 2017 René de Groot All Rights Reserved.
 **------------------------------------------------------------------------------
 ** No part of this file may be reproduced
 ** or transmitted in any form or by any
 ** means, electronic or mechanical, for the
 ** purpose, without the express written
 ** permission of the copyright holder.
 *------------------------------------------------------------------------------
 *
 *   This file is part of "Stay-awake on adb".
 *
 *   "Stay-awake on adb" is free software: you can redistribute it and/or modify
 *   it under the terms of the GNU General Public License as published by
 *   the Free Software Foundation, either version 3 of the License, or
 *   (at your option) any later version.
 *
 *   "Stay-awake on adb" is distributed in the hope that it will be useful,
 *   but WITHOUT ANY WARRANTY; without even the implied warranty of
 *   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *   GNU General Public License for more details.
 *
 *   You should have received a copy of the GNU General Public License
 *   along with "Stay-awake on adb".  If not, see <http://www.gnu.org/licenses/>.
 *
 */
```

You've modified the GPLv3 header and you claim that this software is licensed under GPLv3, yet on the first part of the header you state that:

` No part of this file may be reproduced
 or transmitted in any form or by any
means, electronic or mechanical, for the
 purpose, without the express written
 permission of the copyright holder.`

And you also say `All Rights Reserved`. This is inconsistent and incompatible with the GPL, which states that anyone is free to redistribute or modify the software under GPLv3 terms. In fact, this is not a FOSS license at all.

Can you please clarify this situation?

**Comment by rcgroot** [comment]
The code is copyrighted and then licensed for use. As apposed to is being public domain.

`the express written permission of the copyright holder` is given just a few lines below as `u can redistribute it and/or modify it under the terms of the GNU General Public License`

**Comment by AlvaroBrey** [comment]
I don't think that counts as express written permission, at least in my country express written permission means an actual signed piece of paper.
Apart from that, [the actual GPL3 license header](https://www.gnu.org/licenses/gpl-3.0.en.html#howto) already has a copyright field, so your code wouldn't be public domain either. All licenses I've seen do this, actually.*

In any case, if your intention is to distribute it under the GPL3, that's fine by me. Just wanted to point out that this is, as far as I know, not a valid license.

_Side note_: the GPL3 header also doesn't substitute `this program` for the actual name of the program. The name of the program goes in the first line.
_Side note 2_: the GPL3 cannot be modified and still be valid: `Everyone is permitted to copy and distribute verbatim copies of this license document, but changing it is not allowed.` is in the license.

**Comment by rcgroot** [comment]
I think you are confusing the copyright with a license. Licensing can't exist without copyright.
